version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./plugin:/var/www/html/wp-content/mu-plugins:cached
      - ./uploads:/var/www/html/wp-content/uploads:cached
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WP_DEBUG: 'true'
      WORDPRESS_CONFIG_EXTRA: |
        # define( 'WP_DEBUG_DISPLAY', true );
        # @ini_set( 'display_errors', 1 );
        # Allow cron to process faster
        define('WP_CRON_LOCK_TIMEOUT', 1);
volumes:
  db_data: {}
